{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "1. Importar Librerías y Cargar los Datos\n",
    "(Primera Celda)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 12,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Importar librerías necesarias\n",
    "import pandas as pd\n",
    "import numpy as np\n",
    "from fastapi import FastAPI\n",
    "from fastapi.responses import JSONResponse\n",
    "from fastapi.middleware.cors import CORSMiddleware\n",
    "from pydantic import BaseModel\n",
    "import nest_asyncio\n",
    "from uvicorn import run\n",
    "\n",
    "# Cargar los datasets\n",
    "df_movies = pd.read_csv(\"movies_dataset.csv\", low_memory=False)\n",
    "df_credits = pd.read_csv(\"credits.csv\")"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "2. Exploración Inicial de los Datos (EDA)\n",
    "(Segunda Celda)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 13,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Primeras filas de df_movies:\n",
      "   adult                              belongs_to_collection    budget  \\\n",
      "0  False  {'id': 10194, 'name': 'Toy Story Collection', ...  30000000   \n",
      "1  False                                                NaN  65000000   \n",
      "2  False  {'id': 119050, 'name': 'Grumpy Old Men Collect...         0   \n",
      "3  False                                                NaN  16000000   \n",
      "4  False  {'id': 96871, 'name': 'Father of the Bride Col...         0   \n",
      "\n",
      "                                              genres  \\\n",
      "0  [{'id': 16, 'name': 'Animation'}, {'id': 35, '...   \n",
      "1  [{'id': 12, 'name': 'Adventure'}, {'id': 14, '...   \n",
      "2  [{'id': 10749, 'name': 'Romance'}, {'id': 35, ...   \n",
      "3  [{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...   \n",
      "4                     [{'id': 35, 'name': 'Comedy'}]   \n",
      "\n",
      "                               homepage     id    imdb_id original_language  \\\n",
      "0  http://toystory.disney.com/toy-story    862  tt0114709                en   \n",
      "1                                   NaN   8844  tt0113497                en   \n",
      "2                                   NaN  15602  tt0113228                en   \n",
      "3                                   NaN  31357  tt0114885                en   \n",
      "4                                   NaN  11862  tt0113041                en   \n",
      "\n",
      "                original_title  \\\n",
      "0                    Toy Story   \n",
      "1                      Jumanji   \n",
      "2             Grumpier Old Men   \n",
      "3            Waiting to Exhale   \n",
      "4  Father of the Bride Part II   \n",
      "\n",
      "                                            overview  ... release_date  \\\n",
      "0  Led by Woody, Andy's toys live happily in his ...  ...   1995-10-30   \n",
      "1  When siblings Judy and Peter discover an encha...  ...   1995-12-15   \n",
      "2  A family wedding reignites the ancient feud be...  ...   1995-12-22   \n",
      "3  Cheated on, mistreated and stepped on, the wom...  ...   1995-12-22   \n",
      "4  Just when George Banks has recovered from his ...  ...   1995-02-10   \n",
      "\n",
      "       revenue runtime                                   spoken_languages  \\\n",
      "0  373554033.0    81.0           [{'iso_639_1': 'en', 'name': 'English'}]   \n",
      "1  262797249.0   104.0  [{'iso_639_1': 'en', 'name': 'English'}, {'iso...   \n",
      "2          0.0   101.0           [{'iso_639_1': 'en', 'name': 'English'}]   \n",
      "3   81452156.0   127.0           [{'iso_639_1': 'en', 'name': 'English'}]   \n",
      "4   76578911.0   106.0           [{'iso_639_1': 'en', 'name': 'English'}]   \n",
      "\n",
      "     status                                            tagline  \\\n",
      "0  Released                                                NaN   \n",
      "1  Released          Roll the dice and unleash the excitement!   \n",
      "2  Released  Still Yelling. Still Fighting. Still Ready for...   \n",
      "3  Released  Friends are the people who let you be yourself...   \n",
      "4  Released  Just When His World Is Back To Normal... He's ...   \n",
      "\n",
      "                         title  video vote_average vote_count  \n",
      "0                    Toy Story  False          7.7     5415.0  \n",
      "1                      Jumanji  False          6.9     2413.0  \n",
      "2             Grumpier Old Men  False          6.5       92.0  \n",
      "3            Waiting to Exhale  False          6.1       34.0  \n",
      "4  Father of the Bride Part II  False          5.7      173.0  \n",
      "\n",
      "[5 rows x 24 columns]\n",
      "\n",
      "Primeras filas de df_credits:\n",
      "                                                cast  \\\n",
      "0  [{'cast_id': 14, 'character': 'Woody (voice)',...   \n",
      "1  [{'cast_id': 1, 'character': 'Alan Parrish', '...   \n",
      "2  [{'cast_id': 2, 'character': 'Max Goldman', 'c...   \n",
      "3  [{'cast_id': 1, 'character': \"Savannah 'Vannah...   \n",
      "4  [{'cast_id': 1, 'character': 'George Banks', '...   \n",
      "\n",
      "                                                crew     id  \n",
      "0  [{'credit_id': '52fe4284c3a36847f8024f49', 'de...    862  \n",
      "1  [{'credit_id': '52fe44bfc3a36847f80a7cd1', 'de...   8844  \n",
      "2  [{'credit_id': '52fe466a9251416c75077a89', 'de...  15602  \n",
      "3  [{'credit_id': '52fe44779251416c91011acb', 'de...  31357  \n",
      "4  [{'credit_id': '52fe44959251416c75039ed7', 'de...  11862  \n",
      "\n",
      "Información de df_movies:\n",
      "<class 'pandas.core.frame.DataFrame'>\n",
      "RangeIndex: 45466 entries, 0 to 45465\n",
      "Data columns (total 24 columns):\n",
      " #   Column                 Non-Null Count  Dtype  \n",
      "---  ------                 --------------  -----  \n",
      " 0   adult                  45466 non-null  object \n",
      " 1   belongs_to_collection  4494 non-null   object \n",
      " 2   budget                 45466 non-null  object \n",
      " 3   genres                 45466 non-null  object \n",
      " 4   homepage               7782 non-null   object \n",
      " 5   id                     45466 non-null  object \n",
      " 6   imdb_id                45449 non-null  object \n",
      " 7   original_language      45455 non-null  object \n",
      " 8   original_title         45466 non-null  object \n",
      " 9   overview               44512 non-null  object \n",
      " 10  popularity             45461 non-null  object \n",
      " 11  poster_path            45080 non-null  object \n",
      " 12  production_companies   45463 non-null  object \n",
      " 13  production_countries   45463 non-null  object \n",
      " 14  release_date           45379 non-null  object \n",
      " 15  revenue                45460 non-null  float64\n",
      " 16  runtime                45203 non-null  float64\n",
      " 17  spoken_languages       45460 non-null  object \n",
      " 18  status                 45379 non-null  object \n",
      " 19  tagline                20412 non-null  object \n",
      " 20  title                  45460 non-null  object \n",
      " 21  video                  45460 non-null  object \n",
      " 22  vote_average           45460 non-null  float64\n",
      " 23  vote_count             45460 non-null  float64\n",
      "dtypes: float64(4), object(20)\n",
      "memory usage: 8.3+ MB\n",
      "None\n",
      "\n",
      "Información de df_credits:\n",
      "<class 'pandas.core.frame.DataFrame'>\n",
      "RangeIndex: 45476 entries, 0 to 45475\n",
      "Data columns (total 3 columns):\n",
      " #   Column  Non-Null Count  Dtype \n",
      "---  ------  --------------  ----- \n",
      " 0   cast    45476 non-null  object\n",
      " 1   crew    45476 non-null  object\n",
      " 2   id      45476 non-null  int64 \n",
      "dtypes: int64(1), object(2)\n",
      "memory usage: 1.0+ MB\n",
      "None\n",
      "\n",
      "Columnas en df_movies:\n",
      "Index(['adult', 'belongs_to_collection', 'budget', 'genres', 'homepage', 'id',\n",
      "       'imdb_id', 'original_language', 'original_title', 'overview',\n",
      "       'popularity', 'poster_path', 'production_companies',\n",
      "       'production_countries', 'release_date', 'revenue', 'runtime',\n",
      "       'spoken_languages', 'status', 'tagline', 'title', 'video',\n",
      "       'vote_average', 'vote_count'],\n",
      "      dtype='object')\n",
      "\n",
      "Columnas en df_credits:\n",
      "Index(['cast', 'crew', 'id'], dtype='object')\n"
     ]
    }
   ],
   "source": [
    "# Mostrar las primeras filas de los datasets\n",
    "print(\"Primeras filas de df_movies:\")\n",
    "print(df_movies.head())\n",
    "\n",
    "print(\"\\nPrimeras filas de df_credits:\")\n",
    "print(df_credits.head())\n",
    "\n",
    "# Información general de las columnas y tipos de datos\n",
    "print(\"\\nInformación de df_movies:\")\n",
    "print(df_movies.info())\n",
    "\n",
    "print(\"\\nInformación de df_credits:\")\n",
    "print(df_credits.info())\n",
    "\n",
    "# Listar columnas de cada dataset\n",
    "print(\"\\nColumnas en df_movies:\")\n",
    "print(df_movies.columns)\n",
    "\n",
    "print(\"\\nColumnas en df_credits:\")\n",
    "print(df_credits.columns)\n"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "reduccion df"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 14,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "<class 'pandas.core.frame.DataFrame'>\n",
      "Index: 22738 entries, 26981 to 28031\n",
      "Data columns (total 3 columns):\n",
      " #   Column  Non-Null Count  Dtype \n",
      "---  ------  --------------  ----- \n",
      " 0   cast    22738 non-null  object\n",
      " 1   crew    22738 non-null  object\n",
      " 2   id      22738 non-null  int64 \n",
      "dtypes: int64(1), object(2)\n",
      "memory usage: 710.6+ KB\n",
      "None\n"
     ]
    }
   ],
   "source": [
    "# Tomar una muestra aleatoria del 50% del DataFrame de 'credits.csv'\n",
    "df_credits = df_credits.sample(frac=0.5, random_state=42)\n",
    "\n",
    "# Sobrescribir el archivo CSV original con la muestra aleatoria\n",
    "df_credits.to_csv(\"credits.csv\", index=False)\n",
    "\n",
    "# Verificar las primeras filas para confirmar\n",
    "print(df_credits.info())"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "3. Transformación de Datos (ETL)\n",
    "(Tercera Celda - Desanidar Columnas y Llenar Valores Nulos)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 15,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Desanidar columnas específicas\n",
    "def desanidar_json(json_column):\n",
    "    if isinstance(json_column, str):\n",
    "        try:\n",
    "            return eval(json_column)  # Evaluar como JSON si es posible\n",
    "        except:\n",
    "            return np.nan\n",
    "    return json_column\n",
    "\n",
    "df_movies['belongs_to_collection'] = df_movies['belongs_to_collection'].apply(desanidar_json)\n",
    "df_movies['production_companies'] = df_movies['production_companies'].apply(desanidar_json)\n",
    "\n",
    "# Rellenar valores nulos en 'revenue' y 'budget' con 0\n",
    "df_movies['revenue'] = df_movies['revenue'].fillna(0)\n",
    "df_movies['budget'] = df_movies['budget'].fillna(0)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "(Cuarta Celda - Transformación de Fechas y Columnas Nuevas)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 16,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "Primeras filas después de las transformaciones:\n",
      "                               belongs_to_collection      budget  \\\n",
      "0  {'id': 10194, 'name': 'Toy Story Collection', ...  30000000.0   \n",
      "1                                                NaN  65000000.0   \n",
      "2  {'id': 119050, 'name': 'Grumpy Old Men Collect...         0.0   \n",
      "3                                                NaN  16000000.0   \n",
      "4  {'id': 96871, 'name': 'Father of the Bride Col...         0.0   \n",
      "\n",
      "                                              genres     id original_language  \\\n",
      "0  [{'id': 16, 'name': 'Animation'}, {'id': 35, '...    862                en   \n",
      "1  [{'id': 12, 'name': 'Adventure'}, {'id': 14, '...   8844                en   \n",
      "2  [{'id': 10749, 'name': 'Romance'}, {'id': 35, ...  15602                en   \n",
      "3  [{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...  31357                en   \n",
      "4                     [{'id': 35, 'name': 'Comedy'}]  11862                en   \n",
      "\n",
      "                                            overview popularity  \\\n",
      "0  Led by Woody, Andy's toys live happily in his ...  21.946943   \n",
      "1  When siblings Judy and Peter discover an encha...  17.015539   \n",
      "2  A family wedding reignites the ancient feud be...    11.7129   \n",
      "3  Cheated on, mistreated and stepped on, the wom...   3.859495   \n",
      "4  Just when George Banks has recovered from his ...   8.387519   \n",
      "\n",
      "                                production_companies  \\\n",
      "0     [{'name': 'Pixar Animation Studios', 'id': 3}]   \n",
      "1  [{'name': 'TriStar Pictures', 'id': 559}, {'na...   \n",
      "2  [{'name': 'Warner Bros.', 'id': 6194}, {'name'...   \n",
      "3  [{'name': 'Twentieth Century Fox Film Corporat...   \n",
      "4  [{'name': 'Sandollar Productions', 'id': 5842}...   \n",
      "\n",
      "                                production_countries release_date  \\\n",
      "0  [{'iso_3166_1': 'US', 'name': 'United States o...   1995-10-30   \n",
      "1  [{'iso_3166_1': 'US', 'name': 'United States o...   1995-12-15   \n",
      "2  [{'iso_3166_1': 'US', 'name': 'United States o...   1995-12-22   \n",
      "3  [{'iso_3166_1': 'US', 'name': 'United States o...   1995-12-22   \n",
      "4  [{'iso_3166_1': 'US', 'name': 'United States o...   1995-02-10   \n",
      "\n",
      "       revenue  runtime                                   spoken_languages  \\\n",
      "0  373554033.0     81.0           [{'iso_639_1': 'en', 'name': 'English'}]   \n",
      "1  262797249.0    104.0  [{'iso_639_1': 'en', 'name': 'English'}, {'iso...   \n",
      "2          0.0    101.0           [{'iso_639_1': 'en', 'name': 'English'}]   \n",
      "3   81452156.0    127.0           [{'iso_639_1': 'en', 'name': 'English'}]   \n",
      "4   76578911.0    106.0           [{'iso_639_1': 'en', 'name': 'English'}]   \n",
      "\n",
      "     status                                            tagline  \\\n",
      "0  Released                                                NaN   \n",
      "1  Released          Roll the dice and unleash the excitement!   \n",
      "2  Released  Still Yelling. Still Fighting. Still Ready for...   \n",
      "3  Released  Friends are the people who let you be yourself...   \n",
      "4  Released  Just When His World Is Back To Normal... He's ...   \n",
      "\n",
      "                         title  vote_average  vote_count  release_year  \\\n",
      "0                    Toy Story           7.7      5415.0        1995.0   \n",
      "1                      Jumanji           6.9      2413.0        1995.0   \n",
      "2             Grumpier Old Men           6.5        92.0        1995.0   \n",
      "3            Waiting to Exhale           6.1        34.0        1995.0   \n",
      "4  Father of the Bride Part II           5.7       173.0        1995.0   \n",
      "\n",
      "      return  \n",
      "0  12.451801  \n",
      "1   4.043035  \n",
      "2   0.000000  \n",
      "3   5.090760  \n",
      "4   0.000000  \n",
      "\n",
      "Información del DataFrame después de las transformaciones:\n",
      "<class 'pandas.core.frame.DataFrame'>\n",
      "Index: 45379 entries, 0 to 45465\n",
      "Data columns (total 20 columns):\n",
      " #   Column                 Non-Null Count  Dtype  \n",
      "---  ------                 --------------  -----  \n",
      " 0   belongs_to_collection  4491 non-null   object \n",
      " 1   budget                 45379 non-null  float64\n",
      " 2   genres                 45379 non-null  object \n",
      " 3   id                     45379 non-null  object \n",
      " 4   original_language      45368 non-null  object \n",
      " 5   overview               44438 non-null  object \n",
      " 6   popularity             45377 non-null  object \n",
      " 7   production_companies   45379 non-null  object \n",
      " 8   production_countries   45379 non-null  object \n",
      " 9   release_date           45376 non-null  object \n",
      " 10  revenue                45379 non-null  float64\n",
      " 11  runtime                45130 non-null  float64\n",
      " 12  spoken_languages       45376 non-null  object \n",
      " 13  status                 45296 non-null  object \n",
      " 14  tagline                20398 non-null  object \n",
      " 15  title                  45376 non-null  object \n",
      " 16  vote_average           45376 non-null  float64\n",
      " 17  vote_count             45376 non-null  float64\n",
      " 18  release_year           45376 non-null  float64\n",
      " 19  return                 45379 non-null  float64\n",
      "dtypes: float64(7), object(13)\n",
      "memory usage: 7.3+ MB\n",
      "None\n"
     ]
    }
   ],
   "source": [
    "# 1. Desanidar algunos campos (opcional según lo necesites)\n",
    "\n",
    "# 2. Rellenar valores nulos en 'revenue' y 'budget' con 0\n",
    "df_movies['revenue'] = pd.to_numeric(df_movies['revenue'], errors='coerce').fillna(0)\n",
    "df_movies['budget'] = pd.to_numeric(df_movies['budget'], errors='coerce').fillna(0)\n",
    "\n",
    "# 3. Eliminar valores nulos en 'release_date'\n",
    "df_movies = df_movies.dropna(subset=['release_date']).copy()\n",
    "\n",
    "# 4. Formatear la columna 'release_date' al formato AAAA-mm-dd\n",
    "df_movies.loc[:, 'release_date'] = pd.to_datetime(df_movies['release_date'], errors='coerce').dt.strftime('%Y-%m-%d')\n",
    "\n",
    "# 5. Crear la columna 'release_year' extrayendo el año de la fecha de estreno\n",
    "df_movies.loc[:, 'release_year'] = pd.to_datetime(df_movies['release_date']).dt.year\n",
    "\n",
    "# 6. Crear la columna 'return' (retorno de inversión)\n",
    "df_movies.loc[:, 'return'] = df_movies.apply(\n",
    "    lambda x: x['revenue'] / x['budget'] if x['budget'] > 0 else 0, axis=1\n",
    ")\n",
    "\n",
    "# 7. Eliminar columnas que no serán utilizadas\n",
    "columns_to_drop = ['video', 'imdb_id', 'adult', 'original_title', 'poster_path', 'homepage']\n",
    "df_movies = df_movies.drop(columns=columns_to_drop, errors='ignore').copy()\n",
    "\n",
    "# Verificar cambios\n",
    "print(\"\\nPrimeras filas después de las transformaciones:\")\n",
    "print(df_movies.head())\n",
    "\n",
    "print(\"\\nInformación del DataFrame después de las transformaciones:\")\n",
    "print(df_movies.info())\n",
    "\n",
    "df_movies.to_csv(\"transformed_movies.csv\", index=False)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "(Quinta Celda - Eliminar Columnas y Realizar el Merge)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 17,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Columnas actuales del DataFrame: Index(['belongs_to_collection', 'budget', 'genres', 'id', 'original_language',\n",
      "       'overview', 'popularity', 'production_companies',\n",
      "       'production_countries', 'release_date', 'revenue', 'runtime',\n",
      "       'spoken_languages', 'status', 'tagline', 'title', 'vote_average',\n",
      "       'vote_count', 'release_year', 'return'],\n",
      "      dtype='object')\n"
     ]
    }
   ],
   "source": [
    "# Verificar columnas disponibles antes de intentar eliminarlas\n",
    "print(\"Columnas actuales del DataFrame:\", df_movies.columns)\n",
    "\n",
    "# Eliminar columnas innecesarias (ignorar errores si alguna no existe)\n",
    "columns_to_drop = ['video', 'imdb_id', 'adult', 'original_title', 'poster_path', 'homepage']\n",
    "df_movies = df_movies.drop(columns=columns_to_drop, errors='ignore')\n",
    "\n",
    "# Convertir 'id' a numérico y realizar el merge con df_credits\n",
    "df_credits['id'] = pd.to_numeric(df_credits['id'], errors='coerce')\n",
    "df_movies['id'] = pd.to_numeric(df_movies['id'], errors='coerce')\n",
    "\n",
    "# Realizar el merge\n",
    "df_merged = pd.merge(df_movies, df_credits, on='id', how='left')"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "4. Implementación de la API\n",
    "(Sexta Celda - Configuración de la API)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 18,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Cargar el dataset transformado\n",
    "df = pd.read_csv(\"transformed_movies.csv\", low_memory=False)\n",
    "# Crear la aplicación FastAPI\n",
    "app = FastAPI()\n",
    "\n",
    "# Habilitar CORS (opcional)\n",
    "origins = [\"*\"]\n",
    "app.add_middleware(\n",
    "    CORSMiddleware,\n",
    "    allow_origins=origins,\n",
    "    allow_credentials=True,\n",
    "    allow_methods=[\"*\"],\n",
    "    allow_headers=[\"*\"],\n",
    ")"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "(Séptima Celda - Endpoints de la API)\n",
    "python\n",
    "Copiar código\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 19,
   "metadata": {},
   "outputs": [],
   "source": [
    "@app.get(\"/\")\n",
    "def home():\n",
    "    return {\"message\": \"Bienvenido a la API de Películas\"}\n",
    "\n",
    "@app.get(\"/cantidad_filmaciones_mes/{mes}\")\n",
    "def cantidad_filmaciones_mes(mes: str):\n",
    "    meses = {\n",
    "        \"enero\": 1, \"febrero\": 2, \"marzo\": 3, \"abril\": 4,\n",
    "        \"mayo\": 5, \"junio\": 6, \"julio\": 7, \"agosto\": 8,\n",
    "        \"septiembre\": 9, \"octubre\": 10, \"noviembre\": 11, \"diciembre\": 12\n",
    "    }\n",
    "    mes_num = meses.get(mes.lower())\n",
    "    if mes_num:\n",
    "        cantidad = df[pd.to_datetime(df['release_date']).dt.month == mes_num].shape[0]\n",
    "        return {\"mes\": mes, \"cantidad\": cantidad}\n",
    "    return {\"error\": \"Mes inválido\"}\n",
    "\n",
    "@app.get(\"/cantidad_filmaciones_dia/{dia}\")\n",
    "def cantidad_filmaciones_dia(dia: str):\n",
    "    dias = {\n",
    "        \"lunes\": 0, \"martes\": 1, \"miércoles\": 2, \"jueves\": 3,\n",
    "        \"viernes\": 4, \"sábado\": 5, \"domingo\": 6\n",
    "    }\n",
    "    dia_num = dias.get(dia.lower())\n",
    "    if dia_num is not None:\n",
    "        cantidad = df[pd.to_datetime(df['release_date']).dt.weekday == dia_num].shape[0]\n",
    "        return {\"dia\": dia, \"cantidad\": cantidad}\n",
    "    return {\"error\": \"Día inválido\"}\n",
    "\n",
    "@app.get(\"/score_titulo/{titulo}\")\n",
    "def score_titulo(titulo: str):\n",
    "    resultado = df[df['title'].str.contains(titulo, case=False, na=False)]\n",
    "    if not resultado.empty:\n",
    "        pelicula = resultado.iloc[0]\n",
    "        return {\n",
    "            \"titulo\": pelicula['title'],\n",
    "            \"año\": pelicula['release_year'],\n",
    "            \"score\": pelicula['popularity']\n",
    "        }\n",
    "    return {\"error\": \"Película no encontrada\"}\n",
    "\n",
    "@app.get(\"/votos_titulo/{titulo}\")\n",
    "def votos_titulo(titulo: str):\n",
    "    resultado = df[df['title'].str.contains(titulo, case=False, na=False)]\n",
    "    if not resultado.empty:\n",
    "        pelicula = resultado.iloc[0]\n",
    "        if pelicula['vote_count'] >= 2000:\n",
    "            return {\n",
    "                \"titulo\": pelicula['title'],\n",
    "                \"cantidad_votos\": pelicula['vote_count'],\n",
    "                \"promedio_votos\": pelicula['vote_average']\n",
    "            }\n",
    "        return {\"error\": \"La película no tiene suficientes votos\"}\n",
    "    return {\"error\": \"Película no encontrada\"}"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "(Octava Celda - Continuación de Endpoints)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 20,
   "metadata": {},
   "outputs": [
    {
     "ename": "",
     "evalue": "",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31mEl kernel se bloqueó al ejecutar código en la celda actual o en una celda anterior. \n",
      "\u001b[1;31mRevise el código de las celdas para identificar una posible causa del error. \n",
      "\u001b[1;31mHaga clic <a href='https://aka.ms/vscodeJupyterKernelCrash'>aquí</a> para obtener más información. \n",
      "\u001b[1;31mVea Jupyter <a href='command:jupyter.viewOutput'>log</a> para obtener más detalles."
     ]
    }
   ],
   "source": [
    "@app.get(\"/get_actor/{nombre_actor}\")\n",
    "def get_actor(nombre_actor: str):\n",
    "    actores = df[df['cast'].str.contains(nombre_actor, case=False, na=False)]\n",
    "    if not actores.empty:\n",
    "        retorno_total = actores['return'].sum()\n",
    "        cantidad = actores.shape[0]\n",
    "        promedio = retorno_total / cantidad if cantidad > 0 else 0\n",
    "        return {\n",
    "            \"actor\": nombre_actor,\n",
    "            \"cantidad_filmaciones\": cantidad,\n",
    "            \"retorno_total\": retorno_total,\n",
    "            \"promedio_retorno\": promedio\n",
    "        }\n",
    "    return {\"error\": \"Actor no encontrado\"}\n",
    "\n",
    "@app.get(\"/get_director/{nombre_director}\")\n",
    "def get_director(nombre_director: str):\n",
    "    directores = df[df['crew'].str.contains(nombre_director, case=False, na=False)]\n",
    "    if not directores.empty:\n",
    "        peliculas = []\n",
    "        for _, row in directores.iterrows():\n",
    "            peliculas.append({\n",
    "                \"titulo\": row['title'],\n",
    "                \"fecha_lanzamiento\": row['release_date'],\n",
    "                \"retorno\": row['return'],\n",
    "                \"costo\": row['budget'],\n",
    "                \"ganancia\": row['revenue']\n",
    "            })\n",
    "        retorno_total = directores['return'].sum()\n",
    "        return {\n",
    "            \"director\": nombre_director,\n",
    "            \"retorno_total\": retorno_total,\n",
    "            \"peliculas\": peliculas\n",
    "        }\n",
    "    return {\"error\": \"Director no encontrado\"}"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "5. Ejecución Local\n",
    "(Novena Celda)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "INFO:     Started server process [1588]\n",
      "INFO:     Waiting for application startup.\n",
      "INFO:     Application startup complete.\n",
      "INFO:     Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "INFO:     127.0.0.1:57190 - \"GET /docs HTTP/1.1\" 200 OK\n",
      "INFO:     127.0.0.1:57190 - \"GET /openapi.json HTTP/1.1\" 200 OK\n",
      "INFO:     127.0.0.1:57190 - \"GET /docs HTTP/1.1\" 200 OK\n",
      "INFO:     127.0.0.1:57190 - \"GET /openapi.json HTTP/1.1\" 200 OK\n"
     ]
    }
   ],
   "source": [
    "# Usar nest_asyncio para permitir la ejecución en Jupyter Notebook\n",
    "nest_asyncio.apply()\n",
    "\n",
    "# Ejecutar la aplicación\n",
    "run(app, host=\"0.0.0.0\", port=8000)"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.0"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
